name: Deploy to Neocities

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Generate updates.json (last 20 commits, base=1997)
      - name: Generate updates.json
        run: |
          BASE=1997
          # total commits so we can offset update numbers
          TOTAL=$(( BASE + $(git rev-list --count HEAD) ))
          MAX=20

          echo "[" > updates.json
          i=0

          # iterate last $MAX commits, splitting fields by \x1f
          git log -n $MAX --pretty=format:'%h%x1f%s%x1f%ci' | \
          while IFS=$'\x1f' read -r sha subject date; do
            num=$(( TOTAL - i ))

            # split title / message
            if [[ "$subject" == *-* ]]; then
              title=${subject%%-*}
              message=${subject#*-}
            else
              title="Update #$num"
              message="$subject"
            fi

            # format date to MONTH-day-year
            fmt_date=$(date -d "$date" +"%B-%-d-%Y")

            # escape quotes
            esc_title=$(printf '%s' "$title" | sed 's/"/\\"/g')
            esc_msg=$(printf '%s' "$message" | sed 's/"/\\"/g')

            entry="{\"sha\":\"$sha\",\"number\":$num,\"title\":\"$esc_title\",\"message\":\"$esc_msg\",\"date\":\"$fmt_date\"}"

            # comma separation
            if [ $i -gt 0 ]; then
              echo "," >> updates.json
            fi
            echo "$entry" >> updates.json

            i=$(( i + 1 ))
          done

          echo "]" >> updates.json
          echo "🗒️ Generated updates.json with $i entries, starting at #$TOTAL"
        shell: bash

      # Prepare a deployment folder that excludes .git and .github
      - name: Prepare deployment folder
        run: |
          mkdir deploy
          rsync -av --exclude='.git' --exclude='.github' --exclude='.gitignore' --exclude='README.md' --exclude='*.scss' ./ deploy/

      # Remove sourcemappingURL comments from all CSS files in the deploy folder
      - name: Remove sourceMappingURL from CSS files
        run: |
          find deploy -type f -name "*.css" -exec sed -i 's/\/\*# sourceMappingURL=[^*]*\*\///g' {} \;

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          protected_files: "{assets,json,blog,Thoughts,JS}/*"
          
          neocities_supporter: true
          preview_before_deploy: true
          dist_dir: deploy
