name: Deploy to Neocities

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Incremental updates.json generation (base 1,997)
      - name: Generate incremental updates.json
        run: |
          FILE=updates.json
          BASE=1997

          # Determine last number (or start at BASE)
          if [[ -f $FILE ]]; then
            LAST=$(jq '.[0].number' "$FILE")
          else
            LAST=$BASE
          fi

          NEXT=$(( LAST + 1 ))

          # Grab latest commit info
          MSG=$(git log -1 --pretty=format:'%s')
          DATE=$(git log -1 --pretty=format:'%ci')

          # Build a new JSON object
          NEW_ENTRY=$(jq -n \
            --arg num "$NEXT" \
            --arg msg "$MSG" \
            --arg dt  "$DATE" \
            '{ number: ($num|tonumber), message: $msg, date: $dt }'
          )

          # Prepend into the existing array or create a new one
          if [[ -f $FILE ]]; then
            jq --argjson new "$NEW_ENTRY" '[ $new ] + .' "$FILE" > /tmp/updates.json
          else
            echo "[$NEW_ENTRY]" > /tmp/updates.json
          fi

          mv /tmp/updates.json "$FILE"
          echo "🗒️ Added update #$NEXT to $FILE"
        shell: bash
        
      # Prepare a deployment folder that excludes .git and .github
      - name: Prepare deployment folder
        run: |
          mkdir deploy
          rsync -av --exclude='.git' --exclude='.github' --exclude='.gitignore' --exclude='README.md' --exclude='*.scss' ./ deploy/

      # Remove sourcemappingURL comments from all CSS files in the deploy folder
      - name: Remove sourceMappingURL from CSS files
        run: |
          find deploy -type f -name "*.css" -exec sed -i 's/\/\*# sourceMappingURL=[^*]*\*\///g' {} \;

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          protected_files: "{assets,json,blog,Thoughts,JS}/*"
          
          neocities_supporter: true
          preview_before_deploy: true
          dist_dir: deploy
