name: Deploy to Neocities

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Generate updates.json from the last 20 commits (base 2000)
      - name: Generate updates.json
        run: |
          BASE=2000
          # how many commits total?
          TOTAL_COMMITS=$(git rev-list --count HEAD)
          MAX=20

          # the top label: most recent update number
          TOP=$(( BASE + TOTAL_COMMITS ))

          echo "[" > updates.json
          git log -n $MAX --pretty=format:'%h%x1f%s%x1f%ci' | \
          awk -F"\x1f" -v top="$TOP" -v max="$MAX" '
            {
              idx = NR - 1;
              num = top - idx;
              subj = $2;
              # split on first hyphen:
              split(subj, parts, "-");
              if (index(subj, "-") > 0) {
                title = parts[1];
                message = substr(subj, length(parts[1]) + 2);
              } else {
                title = "Update #" num;
                message = subj;
              }
              # format date via strftime
              cmd = "date -d \"" $3 "\" \"+%B-%-d-%Y\"";
              cmd | getline formatted;
              close(cmd);
              # JSON-escape quotes
              gsub(/"/, "\\\"", title);
              gsub(/"/, "\\\"", message);
              entry = sprintf(
                "{\"sha\":\"%s\",\"number\":%d,\"title\":\"%s\",\"message\":\"%s\",\"date\":\"%s\"}",
                $1, num, title, message, formatted
              );
              printf("%s%s\n", (NR>1?",":""), entry);
            }
          ' >> updates.json
          echo "]" >> updates.json

          echo "🗒️ Wrote updates.json with last $MAX commits, numbered $TOP down to $((TOP-MAX+1))."  
        shell: bash

      # Prepare a deployment folder that excludes .git and .github
      - name: Prepare deployment folder
        run: |
          mkdir deploy
          rsync -av --exclude='.git' --exclude='.github' --exclude='.gitignore' --exclude='README.md' --exclude='*.scss' ./ deploy/

      # Remove sourcemappingURL comments from all CSS files in the deploy folder
      - name: Remove sourceMappingURL from CSS files
        run: |
          find deploy -type f -name "*.css" -exec sed -i 's/\/\*# sourceMappingURL=[^*]*\*\///g' {} \;

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          protected_files: "{assets,json,blog,Thoughts,JS}/*"
          
          neocities_supporter: true
          preview_before_deploy: true
          dist_dir: deploy
